<a href="https://colab.research.google.com/github/amrutha-m-sajeev/Machine-learning/blob/main/irs_flower_species_prediction_using_KNN_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [161]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [162]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [163]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [164]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [165]:
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [167]:
x=df.iloc[:,1:-1].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [168]:
y=df.iloc[:,-1].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [169]:
x.ndim

2

In [170]:
y.ndim

1

In [171]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)
x_train

array([[7.1, 3. , 5.9, 2.1],
       [6.4, 2.9, 4.3, 1.3],
       [5.3, 3.7, 1.5, 0.2],
       [7.2, 3.6, 6.1, 2.5],
       [5.2, 4.1, 1.5, 0.1],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.1, 2.9, 4.7, 1.4],
       [4.4, 2.9, 1.4, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [5.4, 3.4, 1.5, 0.4],
       [5.5, 4.2, 1.4, 0.2],
       [5.9, 3. , 4.2, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.6, 3. , 4.4, 1.4],
       [6.9, 3.1, 4.9, 1.5],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.1, 4.7, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [6.8, 2.8, 4.8, 1.4],
       [5.7, 2.8, 4.1, 1.3],
       [6.2, 3.4, 5.4, 2.3],
       [4.8, 3.4, 1.9, 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [5. , 3.5, 1.6, 0.6],
       [5.6, 2.5, 3.9, 1.1],
       [6.5, 3. , 5.2, 2. ],
       [6.8, 3. , 5.5, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [7.7, 2.8, 6.7, 2. ],
       [7. , 3.2, 4.7, 1.4],
       [4.6, 3.6, 1. , 0.2],
       [4.5, 2

In [172]:
x_test

array([[4.8, 3. , 1.4, 0.1],
       [5.8, 2.6, 4. , 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [4.7, 3.2, 1.3, 0.2],
       [5.6, 2.9, 3.6, 1.3],
       [5. , 3.4, 1.6, 0.4],
       [7.7, 3.8, 6.7, 2.2],
       [6.9, 3.2, 5.7, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.7, 2.6, 3.5, 1. ],
       [5. , 3.2, 1.2, 0.2],
       [6. , 2.7, 5.1, 1.6],
       [5.7, 2.9, 4.2, 1.3],
       [5. , 3.6, 1.4, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.2, 3.5, 1.5, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.6, 3.2, 1.4, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [6.7, 3.1, 4.4, 1.4],
       [4.4, 3. , 1.3, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [5.4, 3.7, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [6. , 2.2, 4. , 1. ],
       [6. , 2.9, 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.8, 2.8, 5.1, 2.4],
       [6.5, 3. , 5.5, 1.8],
       [5.8, 4. , 1.2, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [6.7, 3.1, 5.6, 2.4],
       [5.8, 2.7, 4.1, 1. ],
       [6.3, 3

In [173]:
y_test

array(['Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype=object)

In [174]:
y_train

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica',

In [175]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
x_train


array([[ 1.5627825 , -0.10197727,  1.23332554,  1.19142634],
       [ 0.71569907, -0.33475146,  0.31894473,  0.1423717 ],
       [-0.61543205,  1.52744211, -1.28122168, -1.30007843],
       [ 1.68379442,  1.29466792,  1.34762314,  1.71595366],
       [-0.73644397,  2.4585389 , -1.28122168, -1.43121026],
       [-0.13138437, -0.10197727,  0.26179593,  0.01123987],
       [-0.13138437,  3.15686149, -1.28122168, -1.03781477],
       [ 0.35266331, -0.33475146,  0.54753994,  0.27350353],
       [-1.70453932, -0.33475146, -1.33837048, -1.30007843],
       [-0.37340821, -1.49862245, -0.02394807, -0.25102379],
       [-0.49442013,  0.82911952, -1.28122168, -1.03781477],
       [-0.37340821,  2.6913131 , -1.33837048, -1.30007843],
       [ 0.11063947, -0.10197727,  0.26179593,  0.40463536],
       [ 0.83671099, -0.56752566,  0.49039114,  0.40463536],
       [ 0.9577229 , -0.10197727,  0.37609354,  0.27350353],
       [ 1.32075866,  0.13079693,  0.66183754,  0.40463536],
       [ 1.19974674,  0.

In [176]:
x_test

array([[-1.37616912, -0.17793799, -1.34852456, -1.47617691],
       [-0.1523033 , -1.09304765,  0.11373099, -0.02058414],
       [-0.27468988,  1.65228133, -1.17980277, -1.21152368],
       [-1.4985557 ,  0.27961684, -1.40476516, -1.3438503 ],
       [-0.39707647, -0.4067154 , -0.11123141,  0.11174248],
       [-1.13139596,  0.73717167, -1.23604337, -1.07919707],
       [ 2.17304175,  1.65228133,  1.63222713,  1.30268202],
       [ 1.1939491 ,  0.27961684,  1.06982115,  1.43500863],
       [ 0.45962961,  0.50839426,  0.50741517,  0.50872232],
       [-0.27468988, -1.09304765, -0.167472  , -0.28523737],
       [-1.13139596,  0.27961684, -1.46100576, -1.3438503 ],
       [ 0.09246986, -0.86427024,  0.73237757,  0.50872232],
       [-0.27468988, -0.4067154 ,  0.22621218,  0.11174248],
       [-1.13139596,  1.1947265 , -1.34852456, -1.3438503 ],
       [ 1.80588201, -0.63549282,  1.29478355,  0.90570217],
       [-0.88662279,  0.96594909, -1.29228396, -1.3438503 ],
       [-1.25378254, -1.

In [177]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=7)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica'], dtype=object)

In [178]:
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica'], dtype=object)

In [179]:
print(model.predict([[4,2,1,.3]]))

['Iris-virginica']


In [180]:
pred=model.predict(scaler.transform([[5,3,1,.2]]))
print(pred)

['Iris-setosa']


In [181]:
from sklearn.metrics import confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
result

array([[14,  0,  0],
       [ 0, 15,  1],
       [ 0,  1, 14]])

In [182]:
score=accuracy_score(y_test,y_pred)
score

0.9555555555555556