<a href="https://colab.research.google.com/github/amrutha-m-sajeev/Machine-learning/blob/main/weather_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/seattle-weather.csv')
df

date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [18]:
df.head()

date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [19]:
df.tail()

date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            8.6       4.4       1.7   2.9    rain
1457  2015-12-28            1.5       5.0       1.7   1.3    rain
1458  2015-12-29            0.0       7.2       0.6   2.6     fog
1459  2015-12-30            0.0       5.6      -1.0   3.4     sun
1460  2015-12-31            0.0       5.6      -2.1   3.5     sun

In [20]:
def date_time(df):

    df['date'] = pd.to_datetime(df['date'])
    df['year'] = df['date'].dt.year
    df['month'] = df['date'].dt.month
    return df
df=date_time(df)
df 

date  precipitation  temp_max  temp_min  wind  weather  year  month
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle  2012      1
1    2012-01-02           10.9      10.6       2.8   4.5     rain  2012      1
2    2012-01-03            0.8      11.7       7.2   2.3     rain  2012      1
3    2012-01-04           20.3      12.2       5.6   4.7     rain  2012      1
4    2012-01-05            1.3       8.9       2.8   6.1     rain  2012      1
...         ...            ...       ...       ...   ...      ...   ...    ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain  2015     12
1457 2015-12-28            1.5       5.0       1.7   1.3     rain  2015     12
1458 2015-12-29            0.0       7.2       0.6   2.6      fog  2015     12
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun  2015     12
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun  2015     12

[1461 rows x 8 columns]

In [21]:
df.drop(['date'],axis='columns',inplace=True)
df

precipitation  temp_max  temp_min  wind  weather  year  month
0               0.0      12.8       5.0   4.7  drizzle  2012      1
1              10.9      10.6       2.8   4.5     rain  2012      1
2               0.8      11.7       7.2   2.3     rain  2012      1
3              20.3      12.2       5.6   4.7     rain  2012      1
4               1.3       8.9       2.8   6.1     rain  2012      1
...             ...       ...       ...   ...      ...   ...    ...
1456            8.6       4.4       1.7   2.9     rain  2015     12
1457            1.5       5.0       1.7   1.3     rain  2015     12
1458            0.0       7.2       0.6   2.6      fog  2015     12
1459            0.0       5.6      -1.0   3.4      sun  2015     12
1460            0.0       5.6      -2.1   3.5      sun  2015     12

[1461 rows x 7 columns]

In [23]:
df.columns

Index(['precipitation', 'temp_max', 'temp_min', 'wind', 'weather', 'year',
       'month'],
      dtype='object')

In [24]:
df.isna().sum()

precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
year             0
month            0
dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   precipitation  1461 non-null   float64
 1   temp_max       1461 non-null   float64
 2   temp_min       1461 non-null   float64
 3   wind           1461 non-null   float64
 4   weather        1461 non-null   object 
 5   year           1461 non-null   int64  
 6   month          1461 non-null   int64  
dtypes: float64(4), int64(2), object(1)
memory usage: 80.0+ KB


In [28]:
x=df.drop(['weather'],axis='columns').values
x

array([[ 0.000e+00,  1.280e+01,  5.000e+00,  4.700e+00,  2.012e+03,
         1.000e+00],
       [ 1.090e+01,  1.060e+01,  2.800e+00,  4.500e+00,  2.012e+03,
         1.000e+00],
       [ 8.000e-01,  1.170e+01,  7.200e+00,  2.300e+00,  2.012e+03,
         1.000e+00],
       ...,
       [ 0.000e+00,  7.200e+00,  6.000e-01,  2.600e+00,  2.015e+03,
         1.200e+01],
       [ 0.000e+00,  5.600e+00, -1.000e+00,  3.400e+00,  2.015e+03,
         1.200e+01],
       [ 0.000e+00,  5.600e+00, -2.100e+00,  3.500e+00,  2.015e+03,
         1.200e+01]])

In [30]:
y=df['weather'].values
y

array(['drizzle', 'rain', 'rain', ..., 'fog', 'sun', 'sun'], dtype=object)

In [31]:
x.ndim

2

In [32]:
y.ndim

1

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=42)
x_train

array([[ 6.100e+00,  5.000e+00,  2.800e+00,  7.600e+00,  2.015e+03,
         1.200e+01],
       [ 2.000e+00,  7.800e+00,  2.800e+00,  8.000e-01,  2.014e+03,
         2.000e+00],
       [ 0.000e+00,  2.390e+01,  1.330e+01,  2.200e+00,  2.014e+03,
         7.000e+00],
       ...,
       [ 5.000e-01,  1.560e+01,  7.200e+00,  2.100e+00,  2.014e+03,
         5.000e+00],
       [ 0.000e+00,  5.600e+00, -1.000e+00,  3.400e+00,  2.015e+03,
         1.200e+01],
       [ 0.000e+00,  7.200e+00,  3.300e+00,  1.900e+00,  2.015e+03,
         1.000e+00]])

In [34]:
x_test

array([[0.000e+00, 2.390e+01, 1.110e+01, 2.700e+00, 2.014e+03, 6.000e+00],
       [5.800e+00, 7.800e+00, 6.100e+00, 5.000e-01, 2.015e+03, 1.000e+00],
       [0.000e+00, 9.400e+00, 4.400e+00, 3.400e+00, 2.013e+03, 2.000e+00],
       ...,
       [0.000e+00, 1.440e+01, 8.900e+00, 4.300e+00, 2.013e+03, 3.000e+00],
       [4.300e+00, 1.500e+01, 9.400e+00, 4.300e+00, 2.014e+03, 3.000e+00],
       [0.000e+00, 2.440e+01, 9.400e+00, 4.100e+00, 2.012e+03, 5.000e+00]])

In [35]:
y_train

array(['rain', 'rain', 'sun', ..., 'rain', 'sun', 'fog'], dtype=object)

In [36]:
y_test

array(['sun', 'rain', 'rain', 'sun', 'rain', 'rain', 'rain', 'sun',
       'rain', 'sun', 'sun', 'sun', 'rain', 'sun', 'fog', 'rain', 'sun',
       'fog', 'fog', 'sun', 'rain', 'rain', 'rain', 'sun', 'fog', 'rain',
       'sun', 'sun', 'fog', 'sun', 'rain', 'sun', 'sun', 'snow', 'sun',
       'rain', 'rain', 'rain', 'rain', 'sun', 'rain', 'sun', 'fog', 'sun',
       'sun', 'rain', 'rain', 'sun', 'rain', 'sun', 'sun', 'rain', 'sun',
       'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'sun', 'rain', 'sun',
       'snow', 'sun', 'sun', 'drizzle', 'rain', 'sun', 'rain', 'rain',
       'rain', 'fog', 'sun', 'rain', 'rain', 'sun', 'rain', 'sun', 'rain',
       'snow', 'rain', 'drizzle', 'rain', 'sun', 'rain', 'sun', 'drizzle',
       'rain', 'fog', 'rain', 'rain', 'sun', 'sun', 'rain', 'rain', 'sun',
       'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'rain', 'snow', 'rain',
       'sun', 'sun', 'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'rain',
       'drizzle', 'fog', 'sun', 'sun', 'sun

In [40]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.fit_transform(x_train)
x_test=scalar.fit_transform(x_test)
x_train

array([[ 0.46133235, -1.56004122, -1.09616752,  3.02943991,  1.32982065,
         1.60056979],
       [-0.15455155, -1.18016631, -1.09616752, -1.70932744,  0.43745249,
        -1.30026782],
       [-0.45498272,  1.00411442,  1.00477618, -0.73369887,  0.43745249,
         0.15015099],
       ...,
       [-0.37987493, -0.12194335, -0.21577207, -0.80338663,  0.43745249,
        -0.43001653],
       [-0.45498272, -1.47863945, -1.85650905,  0.10255419,  1.32982065,
         1.60056979],
       [-0.45498272, -1.26156808, -0.99612258, -0.94276214,  1.32982065,
        -1.59035158]])

In [41]:
x_test

array([[-0.45059558,  1.04251015,  0.58467304, -0.35626658,  0.47293388,
        -0.17892229],
       [ 0.41171669, -1.1659653 , -0.40070574, -1.88145392,  1.37171298,
        -1.6281268 ],
       [-0.45059558, -0.94648948, -0.73573452,  0.1290203 , -0.42584522,
        -1.3382859 ],
       ...,
       [-0.45059558, -0.26062754,  0.15110638,  0.75296058, -0.42584522,
        -1.04844499],
       [ 0.18870489, -0.1783241 ,  0.24964425,  0.75296058,  0.47293388,
        -1.04844499],
       [-0.45059558,  1.11109635,  0.24964425,  0.61430718, -1.32462432,
        -0.46876319]])

In [42]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=7)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array(['sun', 'rain', 'rain', 'sun', 'rain', 'rain', 'sun', 'sun', 'rain',
       'sun', 'sun', 'sun', 'rain', 'sun', 'fog', 'rain', 'rain', 'rain',
       'fog', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'rain', 'rain',
       'sun', 'sun', 'sun', 'rain', 'sun', 'sun', 'rain', 'sun', 'rain',
       'rain', 'rain', 'rain', 'sun', 'rain', 'sun', 'rain', 'sun',
       'rain', 'rain', 'rain', 'rain', 'sun', 'sun', 'sun', 'sun', 'sun',
       'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'sun', 'rain', 'sun',
       'rain', 'sun', 'sun', 'sun', 'rain', 'sun', 'rain', 'rain', 'rain',
       'sun', 'rain', 'sun', 'sun', 'rain', 'sun', 'sun', 'rain', 'rain',
       'rain', 'rain', 'rain', 'sun', 'rain', 'sun', 'sun', 'rain', 'sun',
       'rain', 'rain', 'sun', 'sun', 'rain', 'rain', 'sun', 'sun', 'sun',
       'sun', 'rain', 'sun', 'sun', 'rain', 'snow', 'rain', 'sun', 'sun',
       'rain', 'sun', 'sun', 'rain', 'rain', 'rain', 'sun', 'drizzle',
       'rain', 'sun', 'rain', 'sun', 'rain',

In [43]:
y_test

array(['sun', 'rain', 'rain', 'sun', 'rain', 'rain', 'rain', 'sun',
       'rain', 'sun', 'sun', 'sun', 'rain', 'sun', 'fog', 'rain', 'sun',
       'fog', 'fog', 'sun', 'rain', 'rain', 'rain', 'sun', 'fog', 'rain',
       'sun', 'sun', 'fog', 'sun', 'rain', 'sun', 'sun', 'snow', 'sun',
       'rain', 'rain', 'rain', 'rain', 'sun', 'rain', 'sun', 'fog', 'sun',
       'sun', 'rain', 'rain', 'sun', 'rain', 'sun', 'sun', 'rain', 'sun',
       'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'sun', 'rain', 'sun',
       'snow', 'sun', 'sun', 'drizzle', 'rain', 'sun', 'rain', 'rain',
       'rain', 'fog', 'sun', 'rain', 'rain', 'sun', 'rain', 'sun', 'rain',
       'snow', 'rain', 'drizzle', 'rain', 'sun', 'rain', 'sun', 'drizzle',
       'rain', 'fog', 'rain', 'rain', 'sun', 'sun', 'rain', 'rain', 'sun',
       'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'rain', 'snow', 'rain',
       'sun', 'sun', 'rain', 'sun', 'rain', 'rain', 'sun', 'rain', 'rain',
       'drizzle', 'fog', 'sun', 'sun', 'sun

In [44]:
print(model.predict(scalar.transform([[1,35,8,7,2012,12]])))

['sun']


In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
result

array([[  3,   0,   6,   0,   5],
       [  0,   7,   6,   0,  19],
       [  1,   1, 156,   0,  34],
       [  0,   0,   7,   1,   0],
       [  2,   4,  31,   0, 156]])

In [46]:
score=accuracy_score(y_test,y_pred)
score

0.7357630979498861